package org.tnsif.medicinedashboard.entities;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

//it ensures that given class is an entity in a db table
@Entity
public class Medicine {
	
	//private data members
	
	@Id
	//it will create autogenerated id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Integer id;
	private String medicinename;
	private Float price;
	
	//getters and setters
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getMedicinename() {
		return medicinename;
	}
	public void setMedicinename(String medicinename) {
		this.medicinename = medicinename;
	}
	public Float getPrice() {
		return price;
	}
	public void setPrice(Float price) {
		this.price = price;
	}
	
	

}
